artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Fazil463/ml-project-withmlflow/raw/refs/heads/main/diabetes%20dataset.zip
  local_data_file: D:\DataScience\Ml flow project\ml-project-withmlflow\artifacts\data_ingestion\data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: D:\DataScience\Ml flow project\ml-project-withmlflow\artifacts\data_ingestion\Dataset of Diabetes .csv
  STATUS_FILE: artifacts/data_validation/status.txt



# data_transformation:
#   root_dir: artifacts/data_transformation
#   data_path: artifacts/data_ingestion/winequality-red.csv



# model_trainer:
#   root_dir: artifacts/model_trainer
#   train_data_path: artifacts/data_transformation/train.csv
#   test_data_path: artifacts/data_transformation/test.csv
#   model_name: model.joblib



# model_evaluation:
#   root_dir: artifacts/model_evaluation
#   test_data_path: artifacts/data_transformation/test.csv
#   model_path: artifacts/model_trainer/model.joblib
#   metric_file_name: artifacts/model_evaluation/metrics.json






